### ISSUE TITLE
当idl 有子目录时

### ISSUE THREAD

**Issue by sishui** [cloudwego/fastpb#11]
**Describe the bug**

`user.proto`和 `pet.proto` 子文件夹中(如 `idl/user/user.proto`, `idl/pet/pet.proto`)时出现引用，如`pet/pet.proto`中引用了`user/user.proto`， 生成的`user.pb.go`的 中的 `protoreflect.FileDescriptor` 变量名会是`File_user_user_proto`，而`pet.fast.pb.go`中最后一行生成的却是 `var _ = user.File_user_proto`，从而导致报错不可用

**Comment by HeyJavaBean** [comment]
确实有这个问题，感谢反馈。后续我们会修复一下。

**Comment by sishui** [comment]
我尝试提了个pr，麻烦你看看可行不？
