### ISSUE TITLE
提供grpc的插件来兼容kitex的grpc协议

### ISSUE THREAD

**Issue by someview** [cloudwego/fastpb#19]
当前kitex框架时是kitex封装protoc命令的形式来生成grpc的代码。公司当前的grpc框架是用的gogo/protobuf来生成grpc客户端服务端代码。经过测试, 发现fastpb的性能仍然比不上gogo/protobuf，查看对比源码，发现可能是fastpb不够简洁造成的,整体实现原理差不多.

因此，是否可以protoc的形式来生成kitex grpc代码呢:
```
protoc --fastpb_out=... --fastpb_grpcout=...
```
而不是使用kitex，因为里面包含了非常多的冗余的东西:
```
protoc -I . --plugin=protoc-gen-kitex=go\bin\kitex.exe --kitex_out=kitex_gen --kitex_opt="Verbose=true,GenerateMain=true,GenerateInvoker=false,Version=v0.5.2,NoFastAPI=true,ModuleName=example,ServiceName=GoRoomService,Use=,IDLType=protobuf,Includes=.,ThriftOptions=naming_style=golint;ignore_initialisms;gen_setter;gen_deep_equal;compatible_names;frugal_tag,ProtobufOptions=Mecho.proto=example/kitex_gen,IDL=./echo.proto,OutputPath=C:\\project\\example,PackagePrefix=example/kitex_gen,CombineService=false,CopyIDL=false,ProtobufPlugins=gofast::.,Features=,FrugalPretouch=false,ThriftPluginTimeLimit=1m0s,ExtensionFile=,Record=false,RecordCmd=\go\\bin\\kitex.exe;-service;GoRoomService;-module;example;-I;.;-no-fast-api;--protobuf;Mecho.proto=example/kitex_gen;-protobuf-plugin=gofast::.;-v;./echo.proto,TemplateDir=,GenPath=kitex_gen" --kitex_opt=Mecho.proto=example/kitex_gen --gofast_out=. --gofast_opt= ./echo.proto
```

**Comment by HeyJavaBean** [comment]
1. fastpb 只是 protobuf 编解码实现，和 grpc 无关，你可以使用  kitex -no-fast-api 去掉不用，使用 kitex -protoc 和 kitex- protoc-plugin 来添加其他 protoc 参数
2. 在 protobuf 场景，kitex 会给 service 与 method 生成对应的快速创建 client 和 server 的代码，这些是接入 kitex 的必要的代码

**Comment by fengyeall111** [comment]
> 1. fastpb 只是 protobuf 编解码实现，和 grpc 无关，你可以使用  kitex -no-fast-api 去掉不用，使用 kitex -protoc 和 kitex- protoc-plugin 来添加其他 protoc 参数
> 2. 在 protobuf 场景，kitex 会给 service 与 method 生成对应的快速创建 client 和 server 的代码，这些是接入 kitex 的必要的代码

kitex -protoc? 反正我是没找到哈。。。
`kitex -service GoRoomService  -module example  -I .     -protobuf-plugin=gofast::./kitex_gen -v  ./echo.proto` 这是一个echodemo命令。虽然可以生成兼容Google原生的protobuf的echo.pb.go文件，但是kitex采用的仍然是google官方的pb库。
简单说，添加了protobuf编解码的插件，但是生成grpc客户端，服务端代码的时候采用的pb文件不是插件生成的文件，而是fastpb或者google 原生的protobuf

**Comment by HeyJavaBean** [comment]
1. 笔误，kitex -protobuf
2. 「但是kitex采用的仍然是google官方的pb库」，不是的哈，kitex 代码里用的是接口来调用序列化，如果你提供的是官方库，那就是官方库，如果你用 gogo 的覆盖了官方库，那么就是走 gogo 序列化
3. 简单来说，你需要：-no-fast-api 去掉 fastpb，然后使用 -protobuf-plugin=gofast 来让 gogo 生成的序列化代码覆盖掉官方库，就可以使用了。我刚才测试过了。

**Comment by fengyeall111** [comment]
> 1. 笔误，kitex -protobuf
> 2. 「但是kitex采用的仍然是google官方的pb库」，不是的哈，kitex 代码里用的是接口来调用序列化，如果你提供的是官方库，那就是官方库，如果你用 gogo 的覆盖了官方库，那么就是走 gogo 序列化
> 3. 简单来说，你需要：-no-fast-api 去掉 fastpb，然后使用 -protobuf-plugin=gofast 来让 gogo 生成的序列化代码覆盖掉官方库，就可以使用了。我刚才测试过了。

这个是可以使用，kitex这个命令生成的时候好像是需要手动把插件生成的pb文件拷贝过去替换掉fastpb或者原生protobuf库生成的pb文件

**Comment by HeyJavaBean** [comment]
1. fastpb 用 -no-fast-api 或者直接删掉，它和原生pb或者gogo用的是不一样的接口
2.用gogo覆盖pb生成，可能要看下怎么写插件生成路径的参数。因为除了这些内容，kitex 还会在该序列化文件最后追加 service 相关的代码。所以生成 gogo 的时候位置就要直接覆盖原生

**Comment by someview** [comment]
> 1. fastpb 用 -no-fast-api 或者直接删掉，它和原生pb或者gogo用的是不一样的接口
> 
> 2.用gogo覆盖pb生成，可能要看下怎么写插件生成路径的参数。因为除了这些内容，kitex 还会在该序列化文件最后追加 service 相关的代码。所以生成 gogo 的时候位置就要直接覆盖原生

我尝试过了覆盖的方式，不行.
```
modpath=gitlab.dev.wiqun.com/tl/goserver/chat/l3/contract/tl.goprivate.contract.git
includepath=proto
filename=private_service.proto
servicename=GoPrivateService

# 使用kitex生成pb
kitex -no-fast-api -type protobuf -I $includepath  -module $modpath --protobuf \
"M$filename=$modpath/kitex_gen"  "$includepath/$filename"

# 使用gogofast生成生成pb,并覆盖掉默认生成的pb
protoc --gogofast_out=./kitex_gen --proto_path=$includepath $filename
# 使用go mod tidy更新依赖
go mod tidy
```
因为kitex需要接口信息，然而kitex生成的message和service是定义在一个文件里面的，没办法覆盖，只能用合并文件的方式覆盖.
这儿的根本原因在于，kitex这个命令在设计之初，没有考虑其他的protobuf其他的编码方式，导致只有一个-no-fast-api这样的参数可用，而不是说,指定一个和fastpb地位对等的protoc插件给kitex使用.

另外一点是，这个kitex_gen，这个路径在项目里面太难用了，每一个项目肯定有自己的规范，这样强行指定有点糟糕

**Comment by HeyJavaBean** [comment]
1.「导致只有一个-no-fast-api这样的参数可用，而不是说,指定一个和fastpb地位对等的protoc插件给kitex使用.」确实现状是这样的，可能只有合并文件来解决。
2. 嗯，之前有计划给 kitex 工具支持指定自定义目录位置，但还没来得及完成。

**Comment by someview** [comment]
> 1.「导致只有一个-no-fast-api这样的参数可用，而不是说,指定一个和fastpb地位对等的protoc插件给kitex使用.」确实现状是这样的，可能只有合并文件来解决。 2. 嗯，之前有计划给 kitex 工具支持指定自定义目录位置，但还没来得及完成。

将这个生成代码的部分从kitex中独立出来是否可行呢，易于扩展.

**Comment by HeyJavaBean** [comment]
工具生成代码的过程是先调用 protoc 生成 protobuf 序列化代码(或者默认场景是走fastpb来生成pb代码)，然后 kitex tool以protoc插件的形式被peotoc回调，在此基础上额外写rpc相关的信息。

如果要修改的话，需要在 kitex tool 层面来增加对应gogo的序列化代码生成(就像在调用fastpb或者正常pb的位置添加一个选项)

**Comment by someview** [comment]
> 工具生成代码的过程是先调用 protoc 生成 protobuf 序列化代码(或者默认场景是走fastpb来生成pb代码)，然后 kitex tool以protoc插件的形式被peotoc回调，在此基础上额外写rpc相关的信息。
> 
> 如果要修改的话，需要在 kitex tool 层面来增加对应gogo的序列化代码生成(就像在调用fastpb或者正常pb的位置添加一个选项)

阅读了目前kitex处理proto编码部分的代码，尽管proto部分的代码给人感觉有些问题, 但是本身是能支持gogoproto编码的，gogoproto有xxxmarshsal和xxxunmarshal方法, 只是外部的模板里面不支持gogoproto。最终，我已经通过自定义一个kitex-grpc的模板来解决了这个问题.
