### ISSUE TITLE
安装 fastpb 的问题

### ISSUE THREAD

**Issue by TAKHEXI** [cloudwego/fastpb#20]
请问是否遇到过这样的问题：已下载 fastpb@v0.0.4 但提示  does not contain package github.com/cloudwego/fastpb

github.com/cloudwego/fastpb: module github.com/cloudwego/fastpb@latest found (v0.0.4), but does not contain package github.com/cloudwego/fastpb

**Comment by HeyJavaBean** [comment]
可以搜一下go mod相关的问题解决方法
