### ISSUE TITLE
Sizer 与业务字段冲突

### ISSUE THREAD

**Issue by limpo1989** [cloudwego/fastpb#21]
当proto定义种有一个字段命名为`size` 时会与`fastpb`生成的 Size() 方法冲突，虽然可以修改size为其他命名绕过，但是size变量这个太常用了，对于后期切换到fastpb的项目来说改字段名是个很困难的事情（需要考虑旧版客户端兼容性）

```protobuf
message TestMsg {
  int32 size = 1;
}
```

https://github.com/cloudwego/fastpb/blob/6fc453d58b96f588a9fd49bcef9473ffaf943980/fastpb.go#L31-L33

建议解决方案：将`Size`加一个前缀比如 `FastSize`
```go
// Sizer is designed for generating code.
type Sizer interface {
	FastSize() (n int)
}
```

**Comment by HeyJavaBean** [comment]
确实Size方法名会有这个问题。但感觉改名是个比较大的break change，造成的前后版本不兼容可能有点麻烦

**Comment by limpo1989** [comment]
可以考虑生成一个FastSize 同时保留 Size 版本 并标记为废弃 引导后续用户切换到新版接口 如此两个版本后删除Size版接口 以便有足够的时间引导用户切换接口

**Comment by HeyJavaBean** [comment]
涉及到要改动的地方，除了生成代码，还有用到 fastpb 对应接口的地方（比如 kitex 的 codec 代码）。做了改动后用户不一定会及时去更新版本或者重新生成代码，一旦 block 住了用户，影响会比较大。

短期来看可能只能手动把字段名称为 size 的情况给改掉。
