### ISSUE TITLE
导入 google protobuf 报错

### ISSUE THREAD

**Issue by romanticu** [cloudwego/fastpb#9]
**Describe the bug**
Cannot use '&v' (type *wrappers.StringValue) as the type ReaderType does not implement 'Reader' as some methods are missing:FastRead(buf []byte, _type int8, number int32) (n int, err error)

![11](https://user-images.githubusercontent.com/15076030/199642783-c2f4a7b9-0506-4b8b-bdea-97d5f18730cd.png)

Unresolved reference 'File_common_realm_proto'

![2022-11-03 11-46-32屏幕截图](https://user-images.githubusercontent.com/15076030/199644044-164302e5-52e8-49f1-84ae-807675473536.png)

**To Reproduce**
执行了下面命令
kitex -module "gitlab.mvalley.com/fgq/kitex_demo"  -service getinfo ./proto/info/kd.proto

**Screenshots**

本地文件 proto/common_realm/common.proto
![2022-11-03 11-28-43屏幕截图](https://user-images.githubusercontent.com/15076030/199642467-b831112c-9acd-4937-9a36-abd51814aa7f.png)
本地文件 proto_vendor/google/protobuf/wrappers.proto
![2022-11-03 11-29-13屏幕截图](https://user-images.githubusercontent.com/15076030/199642480-19bda8d2-8a1a-4377-80dc-72567b2bbfcd.png)

**fastpb version:**
 Code generated by FastPB v0.0.1.

**Comment by HeyJavaBean** [comment]
fixed, #12
